services:
  - type: web
    name: medical-scoring-api
    env: python
    runtime: python-3.10
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free